version: '3.7'

services:

  db:
    image: postgres:16
    shm_size: 128mb
    volumes:
      - ./postgres-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=discord
      - POSTGRES_PASSWORD=123123
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
