spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/discord-auth
    username: discord
    password: 123123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 123123
  expiration: 3600
